# Generated by Django 4.2.23 on 2025-08-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_newstudent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newstudent',
            table='newstudent',
        ),
    ]
