# Generated by Django 4.2.23 on 2025-08-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_studentmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rollno',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
