# Generated by Django 4.2.23 on 2025-08-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_profile_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rollno',
            field=models.CharField(max_length=20),
        ),
    ]
