# Generated by Django 4.2.23 on 2025-08-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_leave_status_alter_leave_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
