# Generated by Django 4.2.23 on 2025-08-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
